### ISSUE TITLE
Error while trying to download the dataset (Windows)

### ISSUE THREAD

**Issue by ragvri** [A2Zadeh/CMU-MultimodalDataSDK#21]
When I try to download the features of a dataset using `mosei_facet = mosei.facet()` , I get an error:

`>>> from mmdata import Dataloader
>>> mosei = Dataloader('http://sorena.multicomp.cs.cmu.edu/downloads/MOSEI')
>>> mosei_emb = mosei.embeddings()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\models\CMU-MultimodalDataSDK\mmdata\dataloader.py", line 108, in embeddings
    embeddings_values = self.get_feature('embeddings')
  File "D:\models\CMU-MultimodalDataSDK\mmdata\dataloader.py", line 75, in get_feature
    downloaded = download(self.dataset, feature, self.location)
  File "D:\models\CMU-MultimodalDataSDK\mmdata\utils.py", line 37, in download
    call(['mkdir', '-p', dest])
  File "C:\Users\ragha\AppData\Local\Programs\Python\Python35\Lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\ragha\AppData\Local\Programs\Python\Python35\Lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\ragha\AppData\Local\Programs\Python\Python35\Lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`. 

Please help.

**Comment by rhoposit** [comment]
In mmdata/dataloader.py there's a class called Dataloader. There is a line in __init__ where you can specify self.location - this is the path where the data will download. It might not fix your problem but it's easy to try. Also check permissions on that folder (in self.location)

**Comment by A2Zadeh** [comment]
@ragvri there is a compatibility issue with Windows for this line: 

`call(['mkdir', '-p', dest])`

You can replace that with the equivalent command from [this link](https://stackoverflow.com/questions/905226/what-is-equivalent-to-linux-mkdir-p-in-windows?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

**Comment by ragvri** [comment]
I have not been able to figure out what to use in case of windows. Can you please tell me what to write instead?
